ruta = " "*50
print(ruta,"+-----------------+")
print(ruta,"|                 |")
print(ruta,"|    Uppgift 1    |")
print(ruta,"|                 |")
print(ruta,"|   Theodor O.Y   |")
print(ruta,"|                 |")
print(ruta,"|     16/11-22    |")
print(ruta,"|                 |")
print(ruta,"+-----------------+")